### ISSUE TITLE
error running the test code

### ISSUE THREAD

**Issue by twangnh** [leaf1170124460/Mask3D-SHIFT#1]
I was runing the dist_test.sh, 
`bash tools/dist_test.sh projects/configs/detr3d_r101_with_seg_depth_shift_minival.py 1 --checkpoint ./epoch_10.pth --out ./output_pkl.pkl --show-dir output_show --format-only`
got the following error:
```
Traceback (most recent call last):
  File "tools/test.py", line 252, in <module>
    main()
  File "tools/test.py", line 180, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 513, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dist_params'
```
could you pls help

**Comment by leaf1170124460** [comment]
Hi, @twangnh. 
Could you provide more information? such as conda environments by `conda list` and cuda version by `nvcc -V`. 
And you can also check your installed version of mm package is the same as the readme `mmcv-full==1.5.0 mmdet==2.25.0 mmdet3d==1.0.0rc3 mmsegmentation==0.27.0`. It seems that it is an issue caused by version compatibility.

**Comment by twangnh** [comment]
from [conda_list.txt](https://github.com/leaf1170124460/Mask3D-SHIFT/files/11855823/conda_list.txt), it seems the `mmcv-full==1.5.0 mmdet==2.25.0 mmdet3d==1.0.0rc3 mmsegmentation==0.27.0` are correct, `nvcc -V` gives:
```
root@autodl-container-3e5811b1ae-a18f0007:~/autodl-tmp/Mask3d_shift# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
```

**Comment by leaf1170124460** [comment]
It seems that you are using `CUDA 11.0`, but our environment is using `CUDA 11.3`. 
And `torch 1.7.0+cu110` is installed in your environment, which is not consistent with the readme `pytorch==1.10.0`.
Therefore, you can try to change the cuda to 11.3, remove the old environment totally and create a new environment from the readme.

**Comment by twangnh** [comment]
thanks for the reply, I'll try the setting and post the result here

**Comment by twangnh** [comment]
@leaf1170124460 by switching to pytorch==1.10.0 and cuda 11.3, it works correctly with single gpu and python triaining, but when using the command: `bash tools/dist_train.sh projects/configs/detr3d_r101_with_seg_depth_shift_minival.py 4 --auto-resume --no-validate`,
it raises:
```
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/logger/tensorboard.py", line 47, in before_run
    from torch.utils.tensorboard import SummaryWriter
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 13, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 9, in <module>
    from tensorboard.compat.proto.event_pb2 import SessionLog
  File "/root/miniconda3/lib/python3.8/site-packages/tensorboard/compat/proto/event_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/root/miniconda3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /root/miniconda3/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so)
```

I'm wondering which protobuf version is recommended?

**Comment by twangnh** [comment]
by switching to protobuf 3.8.0 it works! 
please consider accept the pull request https://github.com/leaf1170124460/Mask3D-SHIFT/pull/3
