### ISSUE TITLE
no depth img in minival set

### ISSUE THREAD

**Issue by SPA-junghokim** [leaf1170124460/Mask3D-SHIFT#5]
There is no depth img in minival set.
When I downloaded minival set, I can't match the 0000200, 0000300, 0000400 img between img and depth.
There are 0000200, 0000300, 0000400 in img, but There is not in depth folder. Can you check this issue?
When i reproduce your code in my local, It is important for submit good result during 2023 ICCV challenge.

And also, I want to ask to check the minival ground truth file. It is not available to download, now.

Thank you for your attention.

**Comment by leaf1170124460** [comment]
Hi, @SPA-junghokim.
Thank you for your feedback. We apologize for the issue you encountered, but this repo is for issues related to the baseline code. For issues related to the dataset, please create an issue in [shift-dev](https://github.com/SysCV/shift-dev).

**Comment by SPA-junghokim** [comment]
Thank for your reply.
I went to original shift-dev git and I downloaded the dataset from your git download.py. 
However, I could't dowonload some of depth GT from original git. In depth.zip in minival, there is only 0000100.png, not 0000200, 0000300, 0000400.

**Comment by suniique** [comment]
Hey @SPA-junghokim, thanks for the question! You can download all the GTs for depth using [shift-dev](https://github.com/SysCV/shift-dev). For the challenges at VCL, we only evaluate the depth using the frame 0000100 from every sequence due to the resources of our online eval server.
